### PR TITLE
Misc improvements

### LINKED ISSUE #18: Allow multiple servers to be specified
It would be great if I could specify multiple servers so a multi-server production environment would get the same deployment of the latest build.

```
ENV.scp = [
  { 
    username: 'username',
    host: 'server1.example.com',
    path: '/some/path/on/the/server'
  },
  {
    username: 'username',
    host: 'server2.example.com',
    path: '/some/path/on/the/server'
  }
]
```

### PR DESCRIPTION
**Pull request by sandstrom**
Thanks for an excellent plugin @michaljach!

I have some suggested improvements (in separate commits):

1. Some whitespace adjustments
2. Logging rsync command in verbose mode
3. Simplify timestamp (and switch to [iso8601](https://xkcd.com/1179/))
4. Support deploying to multiple nodes

Some questions:

A. For the new multiple nodes, should we deprecate the old config syntax or keep it? E.g. should we switch to only a top-level `nodes` option as the only one outlined in the readme or keep the old syntax in place. (Note that I'm not saying that we should introduce a breaking change here, we should definitely keep the old syntax until a major version bump)

B. I noticed [the existing code](https://github.com/michaljach/ember-cli-deploy-scp/blob/master/index.js#L79-L81) is already using ES6, do you mind if I convert everything to ES6?

C. If we start printing the rsync command in verbose mode, how about removing the `displayCommands` option?

Let me know what you think of this!

Closes #18

### CODE REVIEW

**Comment by michaljach** [comment]
Hey sandstorm!
Thanks for getting involved. Answering your questions:
A. I think we should definitely keep the old syntax
B. Great idea, it should already be full ES6 but I was sloppy ;)
C. Yes, remove it safely

**Comment by sandstrom** [comment]
Just to be clear, my question concerns only what we should put in the readme (we should still support both).

I think it's clearer with only one syntax in the readme (ALT 1).

## Usage (ALT 1)

Edit your `config/deploy.js` file:
```javascript
module.exports = function(environment){
  var ENV = {
  };

  if (environment === 'production') {
    ENV['scp'] = {
        nodes: [{
          username: '<your-username>',
          host: '<your-host>',
          path: '<your-serverpath>'
       }],
    }
  };
  return ENV;
};
```

## Usage (ALT 2)

Edit your `config/deploy.js` file:
```javascript
module.exports = function(environment){
  var ENV = {
  };

  if (environment === 'production') {
    // for a single server, use this
    ENV['scp'] = {
        username: '<your-username>',
        host: '<your-host>',
        path: '<your-serverpath>'
    }

    // for multiple servers, use this
    ENV['scp'] = {
        nodes: [{
          username: '<your-username>',
          host: '<your-host>',
          path: '<your-serverpath>'
       }, /* { next node… } */],
    }
  };

  return ENV;
};
```

**Comment by michaljach** [comment]
Definitely ALT 1, from now on we will encourage users to use this version (staying backwards compatible) and maybe remove old one in the future to get more clean.

**Comment by sandstrom** [comment]
Alright! Should I add a deprecation message when the old syntax is used?

**Comment by michaljach** [comment]
Yep, please add a deprecation message. I can't reopen this as 'the misc branch was force-pushed or recreated'. Maybe this will help https://gist.github.com/robertpainsi/2c42c15f1ce6dab03a0675348edd4e2c

**Comment by sandstrom** [comment]
Alright, I'll open a new PR

**Pull request closed without merging**
