### PR TITLE
remove empty addon folder

### LINKED ISSUE #30: DEPRECATION: Addon files were detected but no JavaScript preprocessors were found
Is there an easy fix for this deprecation error?

`DEPRECATION: Addon files were detected in /Volumes/Home/Sites/searchapp/node_modules/ember-cli-deploy-scp/addon, but no JavaScript preprocessors were found for ember-cli-deploy-scp. Please make sure to add a preprocessor (most likely ember-cli-babel) to in dependencies (NOT devDependencies) in ember-cli-deploy-scp's package.json.`

ember-cli: 2.18.2
node: 8.5.0
os: darwin x64

    "ember-cli-deploy": "^1.0.2",
    "ember-cli-deploy-build": "^1.1.1",
    "ember-cli-deploy-scp": "^1.0.11",

### PR DESCRIPTION
**Pull request by sly7-7**
closes #30

### CODE REVIEW

**Comment by sly7-7** [comment]
Kindly ping @michaljach, this avoids a warning during ember-cli build.

**Comment by michaljach** [comment]
Thank you!

**Comment by DuBistKomisch** [comment]
@michaljach could you release a 1.0.12 with this change?

**Comment by sukima** [comment]
Err, this was merged in **February** over **seven months ago** and yet the latest in NPM is still `1.0.11`.

Is this project dead? What alternatives to this addon are the for ember deploy?

**Comment by michaljach** [comment]
Sorry, This is now released as 1.0.12. Cheers.

**Pull request merged**
